export const travelData = {
    continents: {
      Europa: {
        name: "Europa",
        countries: {
          España: {
            name: "España",
            provinces: ["Madrid", "Barcelona", "Valencia", "Sevilla", "Bilbao"],
          },
          Francia: {
            name: "Francia",
            provinces: ["París", "Lyon", "Marsella", "Niza", "Toulouse"],
          },
          Italia: {
            name: "Italia",
            provinces: ["Roma", "Milán", "Venecia", "Florencia", "Nápoles"],
          },
          Grecia: {
            name: "Grecia",
            provinces: ["Atenas", "Santorini", "Mykonos", "Creta", "Rodas"],
          },
        },
      },
      América: {
        name: "América",
        countries: {
          México: {
            name: "México",
            provinces: ["Cancún", "Playa del Carmen", "Ciudad de México", "Puerto Vallarta", "Los Cabos"],
          },
          Brasil: {
            name: "Brasil",
            provinces: ["Río de Janeiro", "São Paulo", "Salvador", "Florianópolis", "Recife"],
          },
          Argentina: {
            name: "Argentina",
            provinces: ["Buenos Aires", "Mendoza", "Bariloche", "Salta", "Ushuaia"],
          },
          "Estados Unidos": {
            name: "Estados Unidos",
            provinces: ["Nueva York", "Los Ángeles", "Miami", "Las Vegas", "San Francisco"],
          },
        },
      },
      Asia: {
        name: "Asia",
        countries: {
          Japón: {
            name: "Japón",
            provinces: ["Tokio", "Osaka", "Kioto", "Hiroshima", "Nara"],
          },
          Tailandia: {
            name: "Tailandia",
            provinces: ["Bangkok", "Phuket", "Chiang Mai", "Koh Samui", "Pattaya"],
          },
          China: {
            name: "China",
            provinces: ["Pekín", "Shanghái", "Xi'an", "Guilin", "Chengdu"],
          },
          India: {
            name: "India",
            provinces: ["Delhi", "Mumbai", "Goa", "Rajastán", "Kerala"],
          },
        },
      },
      África: {
        name: "África",
        countries: {
          Sudáfrica: {
            name: "Sudáfrica",
            provinces: ["Ciudad del Cabo", "Johannesburgo", "Durban", "Port Elizabeth", "Pretoria"],
          },
          Egipto: {
            name: "Egipto",
            provinces: ["El Cairo", "Luxor", "Asuán", "Alejandría", "Hurghada"],
          },
          Marruecos: {
            name: "Marruecos",
            provinces: ["Marrakech", "Casablanca", "Fez", "Rabat", "Tánger"],
          },
        },
      },
      Oceanía: {
        name: "Oceanía",
        countries: {
          Australia: {
            name: "Australia",
            provinces: ["Sídney", "Melbourne", "Brisbane", "Perth", "Adelaide"],
          },
          "Nueva Zelanda": {
            name: "Nueva Zelanda",
            provinces: ["Auckland", "Wellington", "Christchurch", "Queenstown", "Rotorua"],
          },
        },
      },
    },
    trips: [
      {
        id: 1,
        name: "París Romántico",
        continent: "Europa",
        country: "Francia",
        province: "París",
        price: 1299,
        duration: 7,
        departureDate: "2024-03-15",
        month: "Marzo",
        image: "/placeholder.svg?height=300&width=400",
        hotel: "Hotel Le Meurice",
        flight: "Air France",
        includes: ["hotel", "flight", "breakfast", "tours"],
        description: "Descubre la ciudad del amor con este paquete completo",
        rating: 4.8,
        allInclusive: false,
      },
      {
        id: 2,
        name: "Roma Eterna",
        continent: "Europa",
        country: "Italia",
        province: "Roma",
        price: 1150,
        duration: 6,
        departureDate: "2024-04-20",
        month: "Abril",
        image: "/placeholder.svg?height=300&width=400",
        hotel: "Hotel Artemide",
        flight: "Alitalia",
        includes: ["hotel", "flight", "breakfast"],
        description: "Explora la historia milenaria de la Ciudad Eterna",
        rating: 4.7,
        allInclusive: false,
      },
      {
        id: 3,
        name: "Cancún Todo Incluido",
        continent: "América",
        country: "México",
        province: "Cancún",
        price: 899,
        duration: 5,
        departureDate: "2024-02-10",
        month: "Febrero",
        image: "/placeholder.svg?height=300&width=400",
        hotel: "Moon Palace Cancún",
        flight: "Aeroméxico",
        includes: ["hotel", "flight", "meals", "drinks", "activities"],
        description: "Relájate en las mejores playas del Caribe mexicano",
        rating: 4.9,
        allInclusive: true,
      },
      {
        id: 4,
        name: "Tokio Moderno",
        continent: "Asia",
        country: "Japón",
        province: "Tokio",
        price: 1899,
        duration: 10,
        departureDate: "2024-05-01",
        month: "Mayo",
        image: "/placeholder.svg?height=300&width=400",
        hotel: "Park Hyatt Tokyo",
        flight: "Japan Airlines",
        includes: ["hotel", "flight", "breakfast", "tours"],
        description: "Sumérgete en la cultura japonesa y la tecnología",
        rating: 4.6,
        allInclusive: false,
      },
      {
        id: 5,
        name: "Santorini Mágico",
        continent: "Europa",
        country: "Grecia",
        province: "Santorini",
        price: 1599,
        duration: 8,
        departureDate: "2024-06-15",
        month: "Junio",
        image: "/placeholder.svg?height=300&width=400",
        hotel: "Canaves Oia Hotel",
        flight: "Aegean Airlines",
        includes: ["hotel", "flight", "breakfast", "transfers"],
        description: "Disfruta de las puestas de sol más hermosas del mundo",
        rating: 4.9,
        allInclusive: false,
      },
      {
        id: 6,
        name: "Río de Janeiro Carnaval",
        continent: "América",
        country: "Brasil",
        province: "Río de Janeiro",
        price: 1399,
        duration: 7,
        departureDate: "2024-02-25",
        month: "Febrero",
        image: "/placeholder.svg?height=300&width=400",
        hotel: "Copacabana Palace",
        flight: "LATAM",
        includes: ["hotel", "flight", "breakfast", "carnaval"],
        description: "Vive la fiesta más grande del mundo",
        rating: 4.8,
        allInclusive: false,
      },
      {
        id: 7,
        name: "Bangkok Exótico",
        continent: "Asia",
        country: "Tailandia",
        province: "Bangkok",
        price: 999,
        duration: 9,
        departureDate: "2024-03-10",
        month: "Marzo",
        image: "/placeholder.svg?height=300&width=400",
        hotel: "Mandarin Oriental",
        flight: "Thai Airways",
        includes: ["hotel", "flight", "breakfast", "tours"],
        description: "Descubre los templos y la gastronomía tailandesa",
        rating: 4.5,
        allInclusive: false,
      },
      {
        id: 8,
        name: "Sídney Aventura",
        continent: "Oceanía",
        country: "Australia",
        province: "Sídney",
        price: 2199,
        duration: 12,
        departureDate: "2024-04-05",
        month: "Abril",
        image: "/placeholder.svg?height=300&width=400",
        hotel: "Park Hyatt Sydney",
        flight: "Qantas",
        includes: ["hotel", "flight", "breakfast", "tours"],
        description: "Explora la vibrante ciudad y sus alrededores",
        rating: 4.7,
        allInclusive: false,
      },
      {
        id: 9,
        name: "Marrakech Misterioso",
        continent: "África",
        country: "Marruecos",
        province: "Marrakech",
        price: 799,
        duration: 6,
        departureDate: "2024-05-20",
        month: "Mayo",
        image: "/placeholder.svg?height=300&width=400",
        hotel: "La Mamounia",
        flight: "Royal Air Maroc",
        includes: ["hotel", "flight", "breakfast", "tours"],
        description: "Sumérgete en la magia del norte de África",
        rating: 4.4,
        allInclusive: false,
      },
      {
        id: 10,
        name: "Phuket Paraíso",
        continent: "Asia",
        country: "Tailandia",
        province: "Phuket",
        price: 1199,
        duration: 8,
        departureDate: "2024-07-01",
        month: "Julio",
        image: "/placeholder.svg?height=300&width=400",
        hotel: "Banyan Tree Phuket",
        flight: "Thai Airways",
        includes: ["hotel", "flight", "meals", "spa"],
        description: "Relájate en las playas más hermosas de Tailandia",
        rating: 4.8,
        allInclusive: true,
      },
      {
        id: 11,
        name: "Nueva York Cosmopolita",
        continent: "América",
        country: "Estados Unidos",
        province: "Nueva York",
        price: 1699,
        duration: 5,
        departureDate: "2024-08-15",
        month: "Agosto",
        image: "/placeholder.svg?height=300&width=400",
        hotel: "The Plaza Hotel",
        flight: "American Airlines",
        includes: ["hotel", "flight", "breakfast"],
        description: "Vive la experiencia de la Gran Manzana",
        rating: 4.6,
        allInclusive: false,
      },
      {
        id: 12,
        name: "Barcelona Mediterránea",
        continent: "Europa",
        country: "España",
        province: "Barcelona",
        price: 899,
        duration: 4,
        departureDate: "2024-09-10",
        month: "Septiembre",
        image: "/placeholder.svg?height=300&width=400",
        hotel: "Hotel Casa Fuster",
        flight: "Iberia",
        includes: ["hotel", "flight", "breakfast", "tours"],
        description: "Descubre la arquitectura de Gaudí y la cultura catalana",
        rating: 4.7,
        allInclusive: false,
      },
    ],
  }